// USER SETTINGS
export const SET_USE_PM = "SET_USE_PM";
export const SET_STARTING_WEEKDAY = "SET_STARTING_WEEKDAY";

// SCHEDULER
export const FETCH_SCHEDULE_NODES = "FETCH_SCHEDULE_NODES";
export const ADD_SCHEDULE_NODE = "ADD_SCHEDULE_NODE";
export const EDIT_SCHEDULE_NODE = "EDIT_SCHEDULE_NODE";
export const DELETE_SCHEDULE_NODE = "DELETE_SCHEDULE_NODE";