// SCHEDULER
export const FETCH_SCHEDULE_NODES = "FETCH_SCHEDULE_NODES";
export const ADD_SCHEDULE_NODE = "ADD_SCHEDULE_NODE";
export const EDIT_SCHEDULE_NODE = "EDIT_SCHEDULE_NODE";
export const DELETE_SCHEDULE_NODE = "DELETE_SCHEDULE_NODE";